version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: trello:1.0
    container_name: trello_app
    ports:
      - "30000:3000"
    volumes:
      - ./:/usr/src/nuxt-app